# Generated by Django 5.2.1 on 2025-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_match_result_alter_match_team1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_player1_elo_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_player2_elo_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_player1_elo_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_player2_elo_before',
            field=models.IntegerField(default=0),
        ),
    ]
