# Generated by Django 5.2.1 on 2025-07-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registrationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_player1_trueskill_mu_before',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_player1_trueskill_sigma_before',
            field=models.FloatField(default=8.333333333333334),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_player2_trueskill_mu_before',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_player2_trueskill_sigma_before',
            field=models.FloatField(default=8.333333333333334),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_player1_trueskill_mu_before',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_player1_trueskill_sigma_before',
            field=models.FloatField(default=8.333333333333334),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_player2_trueskill_mu_before',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_player2_trueskill_sigma_before',
            field=models.FloatField(default=8.333333333333334),
        ),
        migrations.AddField(
            model_name='player',
            name='trueskill_mu',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='player',
            name='trueskill_sigma',
            field=models.FloatField(default=8.333333333333334),
        ),
    ]
