# Generated by Django 5.2.1 on 2025-07-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_match_team1_player1_trueskill_mu_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_match_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
