# Generated by Django 5.2.1 on 2026-01-09 15:32

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_player_last_match_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('total_matches', models.IntegerField(default=0)),
                ('total_players', models.IntegerField(default=0)),
                ('statistics', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='year',
            field=models.IntegerField(default=core.models.get_current_year),
        ),
        migrations.AddField(
            model_name='player',
            name='current_year',
            field=models.IntegerField(default=core.models.get_current_year),
        ),
        migrations.CreateModel(
            name='ArchivedPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_email', models.EmailField(max_length=254)),
                ('elo_rating', models.IntegerField()),
                ('trueskill_mu', models.FloatField()),
                ('trueskill_sigma', models.FloatField()),
                ('matches_played', models.IntegerField()),
                ('matches_won', models.IntegerField()),
                ('matches_lost', models.IntegerField()),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='core.yeararchive')),
            ],
            options={
                'ordering': ['-elo_rating'],
                'unique_together': {('archive', 'player_email')},
            },
        ),
    ]
