# Generated by Django 5.2.1 on 2025-05-22 09:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("elo_rating", models.IntegerField(default=1000)),
                ("matches_played", models.IntegerField(default=0)),
                ("matches_won", models.IntegerField(default=0)),
                ("matches_lost", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team1_score", models.IntegerField(default=0)),
                ("team2_score", models.IntegerField(default=0)),
                (
                    "date_played",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("team1_win", "Team 1 Win"),
                            ("team2_win", "Team 2 Win"),
                        ],
                        default="team1_win",
                        max_length=10,
                    ),
                ),
                ("elo_change", models.IntegerField(default=0)),
                (
                    "team1_player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_team1_player1",
                        to="rankings.player",
                    ),
                ),
                (
                    "team1_player2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_team1_player2",
                        to="rankings.player",
                    ),
                ),
                (
                    "team2_player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_team2_player1",
                        to="rankings.player",
                    ),
                ),
                (
                    "team2_player2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_team2_player2",
                        to="rankings.player",
                    ),
                ),
            ],
        ),
    ]
